description: Sample Description
params_desc:
  flags: Param description
  phonecalls_enabled: Param description
  date: Param description
  expires: Param description
  test_mode: Param description
  this_dc: Param description
  dc_options: Param description
  chat_size_max: Param description
  megagroup_size_max: Param description
  forwarded_count_max: Param description
  online_update_period_ms: Param description
  offline_blur_timeout_ms: Param description
  offline_idle_timeout_ms: Param description
  online_cloud_timeout_ms: Param description
  notify_cloud_delay_ms: Param description
  notify_default_delay_ms: Param description
  chat_big_size: Param description
  push_chat_period_ms: Param description
  push_chat_limit: Param description
  saved_gifs_limit: Param description
  edit_time_limit: Param description
  rating_e_decay: Param description
  stickers_recent_limit: Param description
  tmp_sessions: Param description
  pinned_dialogs_count_max: Param description
  call_receive_timeout_ms: Param description
  call_ring_timeout_ms: Param description
  call_connect_timeout_ms: Param description
  call_packet_timeout_ms: Param description
  me_url_prefix: Param description
  disabled_features: Param description
